FROM ghcr.io/classixz/wine:latest

LABEL author="Classixz" maintainer="classixz@undeaduprising.net"

USER root

COPY checkupdater.sh /checkupdater.sh

#Make sure the script is executable by anyone
RUN chmod ugo+x /checkupdater.sh

ENV  USER=container HOME=/home/container/
USER container
WORKDIR /home/container/

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
