FROM ghcr.io/classixz/wine:latest

LABEL author="Classixz" maintainer="classixz@undeaduprising.net"

USER root

RUN apt update && apt upgrade -y \
				&& apt install -y python3.9 python-dev unzip \
				&& apt-cache policy python3.9

COPY checkupdater.sh /checkupdater.sh
COPY GameLogServer.sh /GameLogServer.sh

#Make sure the script is executable by anyone
RUN chmod ugo+x /checkupdater.sh
RUN chmod ugo+x /GameLogServer.sh

ENV  USER=container HOME=/home/container/
USER container
WORKDIR /home/container/

COPY entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
